microservices:
  lcm-bricks:
    docker:
      dockerfile: './Dockerfile'
      arguments:
        BRICKS_VERSION: '{ it -> def dir = new File("."); def result = [] ; dir.eachFile() { file -> result.add(file.path) } ; return result }'
